# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.50.4"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "3024"
   end
   config.vm.provision "shell" do |priv|
    priv.inline = <<-SCRIPT
    yum update
    yum -y install wget git net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
    yum -y --enablerepo=epel install ansible pyOpenSSL
    yum -y install docker-1.12.6 git
    sed -i '/OPTIONS=.*/c\OPTIONS="--selinux-enabled --insecure-registry 172.30.0.0/16"' /etc/sysconfig/docker
    systemctl enable docker
    systemctl start docker
    SCRIPT
    priv.privileged = true
   end
   config.vm.provision "file", source: "../ansiblehosts", destination: "/tmp/ansiblehosts"
   config.vm.provision "shell" do |s|
    s.inline = <<-SCRIPT
    ssh-keygen -f ~/.ssh/id_rsa -N "" && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    if [ ! -d "openshift-ansible" ]; then git clone https://github.com/openshift/openshift-ansible ; fi
    ansible-playbook -i /tmp/ansiblehosts ~/openshift-ansible/playbooks/byo/config.yml
    SCRIPT
    s.privileged = false
   end
end
