# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.50.4"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "3024"
   end
   config.vm.provision "file", source: "../user-data", destination: "/tmp/10_vagrant.cfg"
   config.vm.provision "shell", inline: "yum -y install cloud-init && mv /tmp/10_vagrant.cfg /etc/cloud/cloud.cfg.d/ && echo 'datasource_list: [ None ]' >> /etc/cloud/cloud.cfg && cloud-init -d init && cloud-init -d modules && cloud-init modules -m final"
   config.vm.provision "file", source: "../ansiblehosts", destination: "/tmp/ansiblehosts"
   config.vm.provision "shell" do |s|
    s.inline = <<-SCRIPT
    ssh-keygen -f ~/.ssh/id_rsa -N "" && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    if [ ! -d "openshift-ansible" ]; then git clone https://github.com/openshift/openshift-ansible ; fi
    ansible-playbook -i /tmp/ansiblehosts ~/openshift-ansible/playbooks/byo/config.yml
    SCRIPT
    s.privileged = false
   end
end
