# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "2024"
     vb.cpus = 2
   end
   config.vm.provision "file", source: "../user-data", destination: "/tmp/10_vagrant.cfg"
   config.vm.provision "file", source: "../ansiblehosts", destination: "/tmp/ansiblehosts"
   config.vm.provision "shell", inline: "yum -y install cloud-init && mv /tmp/10_vagrant.cfg /etc/cloud/cloud.cfg.d/ && echo 'datasource_list: [ None ]' >> /etc/cloud/cloud.cfg && cloud-init -d init && cloud-init -d modules && cloud-init modules -m final"
end
